importing jQuery v.>2 and backward compatibility jquery-migrate script this is a way to use admin's Media inner class to allow multiple versions of jQuery. media widget isn't working, may be because of the import order, of which django's jQuery redefinition is last... hence this commit is buggy, throwing TypeError: $(...).mediaWidget is not a function